services:
  keycloak:
    build: containers/keycloak
    container_name: in-delivery-keycloak
    restart: always
    command: start-dev --db postgres # --import-realm
    ports:
      - 8443:8443
    environment:
      KC_DB_URL: jdbc:postgresql://${POSTGRES__HOST}:${POSTGRES__PORT}/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/tls.key
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
  redis:
    image: redis:7
    container_name: in-delivery-redis
    # expose:
      # - 6379
    ports:
      - 6379:6379
    command:
    - /bin/sh
    - -c
    - redis-server --requirepass "$${REDIS__PASSWORD:?REDIS__PASSWORD variable is not set}"
    environment:
      TZ: Europe/Moscow
      REDIS__PASSWORD: ${REDIS__PASSWORD}
  app:
    build: .
    restart: always
    container_name: in-delivery-app
    ports:
      - 8001:8001
    env_file: .env
    depends_on:
      - redis
