services:
  # app:
  #   build: .
  #   container_name: in-delivery-app
  #   ports:
  #     - 8001:8001
  #   env_file: .env
  keycloak:
    build: containers/keycloak
    container_name: in-delivery-keycloak
    restart: always
    command: start-dev --db postgres # --import-realm
    ports:
      - 8443:8443
    environment:
      KC_DB_URL: jdbc:postgresql://${POSTGRES__HOST}:${POSTGRES__PORT}/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/tls.key
    healthcheck:
      test:
        ["CMD", "curl", "--head", "fsS", "https://keycloak:8443/health/ready"]
      interval: 5s
      timeout: 2s
      retries: 15