services:
  budibase:
    image: budibase/budibase
    container_name: in-delivery-budibase
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - budibase-data:/data
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    pull_policy: build
    restart: always
    ports:
      - 443:443
    volumes:
      - caddy-data:/data
      - caddy-config:/config
volumes:
  budibase-data:
  caddy-data:
  caddy-config: